
name: 'ci'
description: 'hello'
inputs:
    who_to_greet:
        description:'wtg'
        required: true
        default: 'world'
outputs:
    time: 
        description:
            'time we greeted you'
runas:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{inputs.who_to_greet}}